seed_everything: null
trainer:
  logger: true
  checkpoint_callback: null
  enable_checkpointing: true
  callbacks: null
  default_root_dir: "/Users/yoni/dlup-lightning-mil-logs/deepsmile-rev/classification/tcga-bc/deepmil/"
  gradient_clip_val: null
  gradient_clip_algorithm: null
  process_position: 0
  num_nodes: 1
  num_processes: 1
  devices: null
  gpus: null
  auto_select_gpus: false
  tpu_cores: null
  ipus: null
  log_gpu_memory: null
  progress_bar_refresh_rate: null
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1
  fast_dev_run: false
  accumulate_grad_batches: null
  max_epochs: null
  min_epochs: null
  max_steps: 100
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 0.1 # Int: Every how many steps to check performance on val? Float: Every how many epochs
  flush_logs_every_n_steps: null
  log_every_n_steps: 50
  accelerator: null
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  weights_summary: top
  weights_save_path: null
  num_sanity_val_steps: 2
  resume_from_checkpoint: null
  profiler: null
  benchmark: false
  deterministic: false
  reload_dataloaders_every_n_epochs: 0
  reload_dataloaders_every_epoch: false
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  prepare_data_per_node: null
  plugins: null
  amp_backend: native
  amp_level: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  stochastic_weight_avg: false
  terminate_on_nan: null
model:
  class_path: dlup_lightning_mil.models.heads.Attention
  init_args:
    num_classes: 2
    in_features: 1024
    hidden_features: 128
    lr: 0.001
model_checkpointing:
  monitor: val_auc
  mode: max # take maximum for e.g. val_auc. take minimum for e.g. loss
  filename: "sample-histo-{epoch:02d}-{step:02d}-{val_loss:.2f}-{val_auc:.2f}-{val_f1:.2f}"
  save_top_k: -1
data:
  class_path: dlup_lightning_mil.data.CompiledH5DataModule
  init_args:
    dataset: "tcga-bc"
    root_dir: "/Users/yoni/dlup-lightning-mil-jobs/deepsmile-rev/data/features/tcga-bc/20wsi"
    train_path: "/Users/yoni/dlup-lightning-mil-jobs/deepsmile-rev/data/features/tcga-bc/20wsi/paths_all_0.txt"
    val_path: "/Users/yoni/dlup-lightning-mil-jobs/deepsmile-rev/data/features/tcga-bc/20wsi/paths_all_0.txt"
    test_path: "/Users/yoni/dlup-lightning-mil-jobs/deepsmile-rev/data/features/tcga-bc/20wsi/paths_all_0.txt"
    num_workers: 0
